experimental-backends = true
backend = "glx"

#                         _ _         
#   ___  _ __   __ _  ___(_) |_ _   _ 
#  / _ \| '_ \ / _` |/ __| | __| | | |
# | (_) | |_) | (_| | (__| | |_| |_| |
#  \___/| .__/ \__,_|\___|_|\__|\__, |
#       |_|                     |___/ 

frame-opacity = 0.90;
opacity-rule = [ "60:class_g = 'Bspwm' && class_i = 'presel_feedback'" ];

#      _               _               
#  ___| |__   __ _  __| | _____      __
# / __| '_ \ / _` |/ _` |/ _ \ \ /\ / /
# \__ \ | | | (_| | (_| | (_) \ V  V / 
# |___/_| |_|\__,_|\__,_|\___/ \_/\_/  
# 

shadow = false;
shadow-radius = 7;
shadow-opacity = 0.55;
shadow-offset-x = -2;
shadow-offset-y = -2;

#   __           _      _             
#  / _| __ _  __| | ___(_)_ __   __ _ 
# | |_ / _` |/ _` |/ _ \ | '_ \ / _` |
# |  _| (_| | (_| |  __/ | | | | (_| |
# |_|  \__,_|\__,_|\___|_|_| |_|\__, |
#                               |___/ 

fading = true;
fade-in-step = 0.01;
fade-out-step = 0.01;
fade-delta = 1; #ms

#   ___ ___  _ __ _ __   ___ _ __ ___ 
#  / __/ _ \| '__| '_ \ / _ \ '__/ __|
# | (_| (_) | |  | | | |  __/ |  \__ \
#  \___\___/|_|  |_| |_|\___|_|  |___/
#                                     

corner-radius = 16;
round-borders = 1;
rounded-corners-exclude = [
	"window_type = 'menu'",
	"window_type = 'dock'",
	"window_type = 'dropdown_menu'",
	"window_type = 'tooltip'",
	# "window_type = 'popup_menu'",
	"window_type = 'utility'",
	"class_g = 'Polybar'",
	"class_g = 'Rofi'",
	"class_g = 'Dunst'",
	"widthb = 2560 && heightb = 1440"
];

#  _     _            
# | |__ | |_   _ _ __ 
# | '_ \| | | | | '__|
# | |_) | | |_| | |   
# |_.__/|_|\__,_|_|   
#                     

blur-background = true; 
blur-strength = 2;
blur-method="dual_kawase";
blur-background-exclude = [
	"_GTK_FRAME_EXTENTS@:c",
	"window_type = 'desktop'",
	"window_type = 'menu'",
	"window_type = 'dock'",
	"window_type = 'dropdown_menu'",
	"window_type = 'popup_menu'",
	"window_type = 'utility'",
	"class_g = 'Rofi'",
	"class_g = 'Dunst'",
	"class_g = 'Polybar'",
	"class_g = 'Bspwm' && class_i = 'presel_feedback'"
]
blur-rule = []
