#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &

xrandr --output HDMI-0 --mode 2560x1440 --refresh 144 --pos 0x0    --rotate normal \
       --output DP-2   --mode 2560x1440 --refresh 75  --pos 2560x0 --rotate normal --primary \
       --output DP-0   --mode 2560x1440 --refresh 75  --pos 5120x0 --rotate normal

feh --bg-fill ~/Pictures/Wallpaper/wallpaper.png

xset r rate 330 50
setxkbmap -option compose:ralt

bspc monitor $(bspc query -M -m primary) -d 1 2 3 4 5 6 7 8 9 10

bspc config focus_follows_pointer true

bspc config window_gap 8
bspc config border_width 2
bspc config focused_border_color  \#808080
bspc config active_border_color   \#404040
bspc config normal_border_color   \#000000
bspc config presel_feedback_color \#404040

eww open bar
